# Generated by Django 4.0.1 on 2022-01-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BesApp', '0002_remove_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cantidad',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
