# Generated by Django 4.0.1 on 2022-01-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BesApp', '0003_alter_compras_cantidad_alter_productos_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='cantidad',
            field=models.BooleanField(null=True),
        ),
    ]
